---
blank_issues_enabled: false
contact_links:
  - name: Madara Community Support
    url: https://github.com/keep-starknet-strange/madara/discussions
    about: Please ask and answer questions here.
